"""empty message

Revision ID: 02c850c7c20b
Revises: 622040702940
Create Date: 2023-10-09 21:06:44.119787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c850c7c20b'
down_revision = '622040702940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histoloss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lossfile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('histoloss_histolossfile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'histolossfile', ['lossfile_id'], ['id'])
        batch_op.drop_column('histolossfile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histoloss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('histolossfile_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('histoloss_histolossfile_id_fkey', 'histolossfile', ['histolossfile_id'], ['id'])
        batch_op.drop_column('lossfile_id')

    # ### end Alembic commands ###
