"""empty message

Revision ID: 89981a0e193f
Revises: cc15d1bc3ad9
Create Date: 2023-09-01 11:03:18.678991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89981a0e193f'
down_revision = 'cc15d1bc3ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lossfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lossfile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('premium', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('loss_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lossfile_id'], ['lossfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.drop_constraint('layer_analysis_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'analysis', ['analysis_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('layer_analysis_id_fkey', 'analysis', ['analysis_id'], ['id'])

    op.drop_table('loss')
    op.drop_table('lossfile')
    # ### end Alembic commands ###
