"""empty message

Revision ID: 938395128c5f
Revises: 498e6ddbcdf5
Create Date: 2023-09-24 12:04:55.136738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '938395128c5f'
down_revision = '498e6ddbcdf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yearlosstable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('view', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yearloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lossfile', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lossfile'], ['yearlosstable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yearlosstables',
    sa.Column('yearlosstable_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['yearlosstable_id'], ['yearlosstable.id'], ),
    sa.PrimaryKeyConstraint('yearlosstable_id', 'layer_id')
    )
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurant', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('review_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant'], ['restaurant.id'], name='review_restaurant_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='review_pkey')
    )
    op.drop_table('yearlosstables')
    op.drop_table('yearloss')
    op.drop_table('yearlosstable')
    # ### end Alembic commands ###
