"""empty message

Revision ID: a06f3158e5dc
Revises: 938395128c5f
Create Date: 2023-09-24 12:27:57.666230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06f3158e5dc'
down_revision = '938395128c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yearlosstable', schema=None) as batch_op:
        batch_op.alter_column('view',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yearlosstable', schema=None) as batch_op:
        batch_op.alter_column('view',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
