"""empty message

Revision ID: ba7e7a7d058f
Revises: 
Create Date: 2023-11-10 15:28:37.069052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7e7a7d058f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('quote', sa.Integer(), nullable=True),
    sa.Column('client', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histolossfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('vintage', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('premium', sa.Integer(), nullable=True),
    sa.Column('deductible', sa.Integer(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premiumfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricingrelationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riskprofilefile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histoloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('premium', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('loss_ratio', sa.Float(), nullable=True),
    sa.Column('lossfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lossfile_id'], ['histolossfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layertomodelfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('pricingrelationship_id', sa.Integer(), nullable=True),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('modelfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['modelfile_id'], ['modelfile.id'], ),
    sa.ForeignKeyConstraint(['pricingrelationship_id'], ['pricingrelationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelyearloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('modelfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modelfile_id'], ['modelfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('premiumfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['premiumfile_id'], ['premiumfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('pricingrelationship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['pricingrelationship_id'], ['pricingrelationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riskprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('riskprofilefile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['riskprofilefile_id'], ['riskprofilefile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultyearloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('grossloss', sa.Integer(), nullable=True),
    sa.Column('recovery', sa.Integer(), nullable=True),
    sa.Column('netloss', sa.Integer(), nullable=True),
    sa.Column('resultfile_id', sa.Integer(), nullable=True),
    sa.Column('layertomodelfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layertomodelfile_id'], ['layertomodelfile.id'], ),
    sa.ForeignKeyConstraint(['resultfile_id'], ['resultfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultyearloss')
    op.drop_table('riskprofile')
    op.drop_table('resultfile')
    op.drop_table('premium')
    op.drop_table('modelyearloss')
    op.drop_table('layertomodelfile')
    op.drop_table('histoloss')
    op.drop_table('riskprofilefile')
    op.drop_table('pricingrelationship')
    op.drop_table('premiumfile')
    op.drop_table('modelfile')
    op.drop_table('layer')
    op.drop_table('histolossfile')
    op.drop_table('analysis')
    # ### end Alembic commands ###
