"""empty message

Revision ID: cc15d1bc3ad9
Revises: ebfb79110b2e
Create Date: 2023-08-29 11:39:56.676148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc15d1bc3ad9'
down_revision = 'ebfb79110b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_column('quote')

    # ### end Alembic commands ###
