"""empty message

Revision ID: d8d44bb0801c
Revises: a06f3158e5dc
Create Date: 2023-09-24 13:25:15.349555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d44bb0801c'
down_revision = 'a06f3158e5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yearloss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yearlosstable_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('yearloss_lossfile_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'yearlosstable', ['yearlosstable_id'], ['id'])
        batch_op.drop_column('lossfile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yearloss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lossfile', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('yearloss_lossfile_fkey', 'yearlosstable', ['lossfile'], ['id'])
        batch_op.drop_column('yearlosstable_id')

    # ### end Alembic commands ###
